package net.silve.smtpc.client.fsm;

public enum SmtpCommandAction {

    HELO, EHLO,
    STARTTLS, TLS_HANDSHAKE,
    PIPELINING_MAIL, PIPELINING_RCPT, PIPELINING_DATA,
    MAIL, RCPT,
    DATA,
    PIPELINING_MAIL_RESPONSE, PIPELINING_RCPT_RESPONSE, PIPELINING_DATA_RESPONSE,
    DATA_CONTENT,
    RSET,
    QUIT,
    CLOSE_TRANSMISSION

}
